services:
  - type: web
    name: ai-interviewer-frontend
    runtime: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://ai-interviewer-backend-u989.onrender.com
