services:
  - type: web
    name: ai-interviewer-backend
    runtime: python
    plan: starter
    buildCommand: |
      export CARGO_HOME=/tmp/cargo
      export PIP_NO_BUILD_ISOLATION=1
      pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ai-interviewer-db
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_ENVIRONMENT
        value: us-west1-gcp
      - key: PINECONE_INDEX_NAME
        value: ai-interviewer
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "30"
      - key: ALLOWED_ORIGINS
        value: "https://ai-interviewer-frontend-gl33.onrender.com"
      - key: DEBUG
        value: "false"
      - key: UPLOAD_DIR
        value: "uploads"
      - key: MAX_FILE_SIZE
        value: "10485760"
      - key: MAX_INTERVIEW_DURATION
        value: "60"
      - key: DEFAULT_QUESTION_COUNT
        value: "10"
      - key: CARGO_HOME
        value: "/tmp/cargo"
      - key: PIP_NO_BUILD_ISOLATION
        value: "1"

databases:
  - name: ai-interviewer-db
    plan: starter
